---
version: '2.3'
services:
  gradle:
    image: gradle:4.9-jdk8
    user: root
    volumes:
      - "$HOME/.aws:/root/.aws"
      - "$HOME/.m2:/root/.m2"
      - "$HOME/.gradle:/root/.gradle"
      - ".:/app"
    working_dir: /app
    environment:
      - BUILDKITE_REPO
      - BUILDKITE_BRANCH
      - BUILDKITE_COMMIT
      - BUILDKITE_BUILD_URL
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BUILD_CREATOR
      - AWS_DEFAULT_REGION
      - AWS_PROFILE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    depends_on:
      - hub
      - chrome

  cmd-helper:
    image: 232859778855.dkr.ecr.ap-southeast-2.amazonaws.com/paycorp-cmd-helper:latest
    volumes:
      - "$HOME/.aws:/root/.aws"
      - ".:/app"
    environment:
      AWS_DEFAULT_REGION:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:
      AWS_PROFILE:
    working_dir: /app

  chrome:
    image: selenium/node-chrome:3.14.0-europium
    volumes:
      - ".:/build"
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    scale: 3

  hub:
    image: selenium/hub:3.14.0-europium
    ports:
      - "4444:4444"
    environment:
      - GRID_NEW_SESSION_WAIT_TIMEOUT=60
      - GRID_TIMEOUT=60
